version: "3.9"
services:
  srv1.example.com:
    build: .
    expose:
      - "8000"
  srv2.example.com:
    build: .
    expose:
      - "8000"
  srv3.example.com:
    build: .
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\";'"
    depends_on:
      - srv1.example.com
      - srv2.example.com
      - srv3.example.com
